spring:
  datasource:
    url: jdbc:sqlserver://cs544group3.database.windows.net:1433;databaseName=group3;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: admingroup3
    password: cS544Group3
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true # Set it to false in production